/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
        display: ['"Inter Tight"', 'Inter', '-apple-system', 'BlinkMacSystemFont', '"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['"SF Mono"', '"Fira Code"', 'ui-monospace', 'monospace'],
      },
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        surfaceHover: 'var(--surfaceHover)',
        border: 'var(--border)',
        borderLight: 'var(--borderLight)',
        text: 'var(--text)',
        textMuted: 'var(--textMuted)',
        textDim: 'var(--textDim)',
        primary: 'var(--primary)',
        primaryHover: 'var(--primaryHover)',
        primaryText: 'var(--primaryText)',
        secondary: 'var(--secondary)',
        secondaryHover: 'var(--secondaryHover)',
        secondaryText: 'var(--secondaryText)',
        input: 'var(--input)',
        'focus-ring': 'var(--focus-ring)',
        error: 'var(--error)',
        errorBg: 'var(--errorBg)',
      },
      borderRadius: {
        sm: '5px',
        DEFAULT: '8px',
        md: '12px',
        lg: '18px',
        xl: '28px',
        '2xl': '36px',
        pill: '980px',
      },
      fontSize: {
        'hero-xl': ['80px', { lineHeight: '1.05', letterSpacing: '-0.015em', fontWeight: '600' }],
        'hero': ['56px', { lineHeight: '1.07', letterSpacing: '-0.005em', fontWeight: '600' }],
        'section': ['48px', { lineHeight: '1.08', letterSpacing: '-0.003em', fontWeight: '600' }],
        'product': ['40px', { lineHeight: '1.10', fontWeight: '600' }],
        'promo': ['32px', { lineHeight: '1.12', fontWeight: '600' }],
        'card-title': ['28px', { lineHeight: '1.14', fontWeight: '600' }],
        'utility': ['24px', { lineHeight: '1.17', fontWeight: '600' }],
        'link-lg': ['21px', { lineHeight: '1.24', fontWeight: '600' }],
        subhead: ['19px', { lineHeight: '1.21', fontWeight: '600' }],
        body: ['17px', { lineHeight: '1.47' }],
        'body-emphasis': ['17px', { lineHeight: '1.24', fontWeight: '600' }],
        control: ['14px', { lineHeight: '1.35' }],
        micro: ['12px', { lineHeight: '1.25' }],
        legal: ['10px', { lineHeight: '1.35' }],
      },
    },
  },
  plugins: [],
}
